services:
  auth:
    image: auth-service:latest
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: auth
    networks:
      - rabbitmq_default
    ports:
      - '3030:3030'
    volumes:
      - data:/app/data/db
    environment:
      NODE_ENV: development

networks:
  rabbitmq_default:
    external: true

volumes:
  data:
